language: csharp
dotnet: 2.1.105
install:
  - mono .paket/paket.bootstrapper.exe
  - mono .paket/paket.exe restore
  - msbuild /t:restore

script:
  - msbuild /property:Configuration=Release FSharp.Compatibility.sln
  - dotnet test --no-build --configuration Release ./FSharp.Compatibility.OCaml.Tests/bin/
  - dotnet test --no-build --configuration Release ./FSharp.Compatibility.OCaml.System.Tests/

